---

- name: install dependencies
  become: true
  apt:
    name:
      - autoconf
      - automake
      - avahi-daemon
      - build-essential
      - git
      - libasound2-dev
      - libavahi-client-dev
      - libconfig-dev
      - libdaemon-dev
      - libpopt-dev
      - libssl-dev
      - libtool
      - xmltoman
    state: present


- name: Create directory for source code
  file:
    path: /home/{{ ansible_ssh_user }}/src
    state: directory

- name: Clone shairport sync pepository
  git:
    repo: https://github.com/mikebrady/shairport-sync
    dest: /home/{{ ansible_ssh_user }}/src/shairport-sync
    version: master

- name: Install auxiliary files
  command: /usr/bin/autoreconf -fi
  args:
    chdir: /home/{{ ansible_ssh_user }}/src/shairport-sync
    creates: /home/{{ ansible_ssh_user }}/src/shairport-sync/configure

- name: Produce customised Makefile
  command: >
      ./configure --sysconfdir=/etc \
                  --with-alsa \
                  --with-avahi \
                  --with-ssl=openssl \
                  --with-systemd
  args:
    chdir: /home/{{ ansible_ssh_user }}/src/shairport-sync
    creates: /home/{{ ansible_ssh_user }}/src/shairport-sync/Makefile

- name: Build shairport-sync
  command: make
  args:
    chdir: /home/{{ ansible_ssh_user }}/src/shairport-sync
    creates: /home/{{ ansible_ssh_user }}/src/shairport-sync/shairport-sync

- name: Copy the program, libraries, and documentation to the correct locations
  become: true
  command: make install
  args:
    chdir: /home/{{ ansible_ssh_user }}/src/shairport-sync
    creates: /usr/bin/shairport-sync

- name: Configure shairport-sync using template
  become: true
  template:
    src: shairport-sync.conf.j2
    dest: /etc/shairport-sync.conf
    backup: true

- name: Set up usb sound card
  become: true
  when: {{ useUsbSound }}
  lineinfile:
    path: /usr/share/alsa/alsa.conf
    regexp: '.*defaults.ctl.card \d'
    line: 'defaults.ctl.card 1'
    create: true
    backup: true

- name: Set up usb sound card
  become: true
  when: {{ useUsbSound }}
  lineinfile:
    path: /usr/share/alsa/alsa.conf
    regexp: '.*defaults.pcm.card \d'
    line: 'defaults.pcm.card 1'
    create: true
    backup: true

- name: ensure or create override directory
  become: true
  file:
    path: /etc/systemd/system/shairport-sync.service.d
    state: directory

- name: make shairport-sync auto restart
  become: true
  copy:
    src: shairport.conf
    dest: /etc/systemd/system/shairport-sync.service.d/override.conf

- name: enable shairport-sync service
  become: true
  systemd:
    daemon_reload: true
    name: shairport-sync
    enabled: true
