---
- name: update pip
  pip:
    name: pip
    state: latest

- name: install virtualenv
  apt:
    name: virtualenv

- name: Install docker
  pip:
    name: docker
    virtualenv: /opt/ansible_env
    version: 4.0.2

- name: Install docker-compose
  pip:
    name: docker-compose
    virtualenv: /opt/ansible_env

- name: build and run homebridge
  docker_compose:
    project_name: homebridge
    definition:
      version: '2'
      services:
        homebridge:
          image: oznu/homebridge:raspberry-pi
          restart: always
          network_mode: host
          volumes:
            - ./config:/homebridge
          environment:
            - PGID=1000
            - PUID=1000
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_CONFIG_UI_PORT={{ homebridge_ui_port }}
  vars:
    ansible_python_interpreter: /opt/ansible_env/bin/python
  register: output

- name: homebridge docker output
  debug:
    var: output
