---
- name: Install proper JDK
  apt:
    name: openjdk-8-jre-headless
    state: present

- name: Install haveged to populate /dev/rand
  apt:
    name: haveged
    state: present

- name: Add unifi PPA key
  apt_key:
    url: https://dl.ubnt.com/unifi/unifi-repo.gpg
    state: present

- name: Install unifi PPA
  apt_repository:
    repo: deb http://www.ui.com/downloads/unifi/debian stable ubiquiti
    state: present

- name: Install unifi package
  apt:
    update_cache: yes
    name: unifi
    state: present
